//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColegioArceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abono
    {
        public int id_Abono { get; set; }
        public decimal Importe { get; set; }
        public System.DateTime Fecha { get; set; }
        public int id_Pago { get; set; }
        public bool Cancelado { get; set; }
        public string TipoPago { get; set; }
        public int Folio { get; set; }
    
        public virtual Pago Pago { get; set; }
    }
}
