//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColegioArceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoAlumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrupoAlumno()
        {
            this.Pago = new HashSet<Pago>();
        }
    
        public int id_GrupoAlumno { get; set; }
        public int id_Grupo { get; set; }
        public int id_Alumno { get; set; }
        public int Anio { get; set; }
        public bool Activo { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Grupo Grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
    }
}
